import { execSync } from "node:child_process";
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const INPUT = "src/forms/client/enhance.ts";
const OUTPUT_JS = ".alchemy/forms-enhance.js";
const OUTPUT_TS = "src/forms/client/enhance.generated.ts";

// Ensure output directory exists
mkdirSync(dirname(OUTPUT_JS), { recursive: true });

// Bundle with esbuild
console.log("Bundling forms enhancement script...");
execSync(`pnpm exec esbuild ${INPUT} --bundle --minify --format=iife --outfile=${OUTPUT_JS}`, {
  stdio: "inherit",
});

// Read the bundled JS
const js = readFileSync(OUTPUT_JS, "utf-8");

// Ensure output directory exists
mkdirSync(dirname(OUTPUT_TS), { recursive: true });

// Write as TypeScript module for inlining
const tsContent = `// AUTO-GENERATED by scripts/build-forms-client.ts - DO NOT EDIT
export const formsEnhanceScript = ${JSON.stringify(js)};
`;

writeFileSync(OUTPUT_TS, tsContent);
console.log(`Generated ${OUTPUT_TS} (${js.length} bytes)`);
