import { execSync } from "node:child_process"
import { writeFileSync, readFileSync, mkdirSync } from "node:fs"
import { dirname } from "node:path"

const OUTPUT_CSS = ".alchemy/tailwind.css"
const OUTPUT_TS = "src/styles/tailwind.generated.ts"

// Ensure output directory exists
mkdirSync(dirname(OUTPUT_CSS), { recursive: true })

// Run Tailwind CLI
console.log("Compiling Tailwind CSS...")
execSync(
  `npx @tailwindcss/cli -i src/styles/tailwind.css -o ${OUTPUT_CSS} --minify`,
  { stdio: "inherit" },
)

// Read the generated CSS
const css = readFileSync(OUTPUT_CSS, "utf-8")

// Write as TypeScript module
const tsContent = `// AUTO-GENERATED by scripts/build-css.ts - DO NOT EDIT
export const tailwindCSS = ${JSON.stringify(css)}
`

mkdirSync(dirname(OUTPUT_TS), { recursive: true })
writeFileSync(OUTPUT_TS, tsContent)

console.log(`Generated ${OUTPUT_TS} (${css.length} bytes)`)
