/**
 * Embed Client Bundle Script
 *
 * This script reads the Vite-built client bundle and generates a TypeScript
 * module that exports it as a string. This allows the Worker to serve the
 * JavaScript inline without needing a separate static file hosting solution.
 *
 * Similar to how build-css.ts embeds Tailwind CSS.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname } from "node:path"

const INPUT_JS = "dist/client/assets/entry-client.js"
const OUTPUT_TS = "src/lib/client-bundle.generated.ts"

// Read the Vite-built client bundle
console.log("Embedding client bundle...")
const clientJS = readFileSync(INPUT_JS, "utf-8")

// Write as TypeScript module
const tsContent = `// AUTO-GENERATED by scripts/embed-client.ts - DO NOT EDIT
// This is the Vite-built React client bundle for hydration
export const clientBundle = ${JSON.stringify(clientJS)}
`

mkdirSync(dirname(OUTPUT_TS), { recursive: true })
writeFileSync(OUTPUT_TS, tsContent)

console.log(`Generated ${OUTPUT_TS} (${clientJS.length} bytes)`)
